Setup LAMP Stack
- hosts: localhost
  tasks:
    - name: installing the lamp stack
      become: yes
      become_user: root
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - apache2
        - mysql-server
        - php
        - php-mysql

    - name: starting the services
      service: name={{ item }} state=started enabled=yes
      become: yes
      become_user: root
      with_items:
        - apache2
        - mysql

    - name: deploy index.html
      become: yes
      become_user: root
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html